### ISSUE TITLE
Добавить добавить чтение токена в header

### ISSUE THREAD

**Issue by oberdev** [egsam98/testing-system#4]
На серверной стороне реализовать чтение токена из Header
Ключ где содержится токен: Authorization

**Comment by egsam98** [comment]
> На серверной стороне реализовать чтение токена из Header
> Ключ где содержится токен: Authorization

[https://github.com/egsam98/testing-system/commit/124da4ab64ec6a0bfaea042569b53bb0bdf62d70](url)
